name: EvoBot
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.10
  - python=3.10.12
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - accelerate==1.0.1
    - aiofiles==24.1.0
    - aiohttp==3.8.5
    - aiohttp-cors==0.7.0
    - aiorwlock==1.3.0
    - aiosignal==1.3.1
    - altair==5.4.0
    - annotated-types==0.7.0
    - anthropic==0.31.1
    - antlr4-python3-runtime==4.8
    - anyio==3.7.1
    - appdirs==1.4.4
    - astroid==3.0.1
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - attrs==23.2.0
    - audioread==3.0.1
    - av==12.3.0
    - backoff==2.2.1
    - bitarray==2.9.2
    - bitvector==3.5.0
    - black==23.10.0
    - blessed==1.20.0
    - blinker==1.8.2
    - build==1.0.3
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.17.0
    - chardet==3.0.4
    - charset-normalizer==3.2.0
    - chex==0.1.7
    - civrealm==0.1.2
    - click==8.1.7
    - cloudpickle==2.2.1
    - cmake==3.27.4.1
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - colorful==0.5.5
    - community==1.0.0b1
    - compressed-tensors==0.6.0
    - contextlib2==21.6.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - cython==3.0.11
    - dataclasses-json==0.6.4
    - datasets==3.1.0
    - decorator==5.1.1
    - deprecated==1.2.14
    - dill==0.3.8
    - diskcache==5.6.3
    - distlib==0.3.7
    - distro==1.9.0
    - dm-env==1.6
    - dm-haiku==0.0.11
    - dm-meltingpot==2.2.0
    - dm-reverb==0.10.0
    - dm-tree==0.1.8
    - dmlab2d==1.0.0
    - docker==7.1.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docstring-parser==0.16
    - einops==0.8.0
    - etils==1.6.0
    - exceptiongroup==1.1.3
    - execnet==2.0.2
    - factories==1.2.0
    - fairseq==0.12.2
    - faiss-cpu==1.7.3
    - farama-notifications==0.0.4
    - fastapi==0.115.4
    - ffmpeg-python==0.2.0
    - ffmpy==0.3.1
    - filelock==3.12.2
    - flask==3.0.3
    - flatbuffers==23.5.26
    - flax==0.7.5
    - fonttools==4.42.1
    - frozenlist==1.4.0
    - fsspec==2023.9.0
    - future==1.0.0
    - gast==0.4.0
    - gguf==0.10.0
    - gitdb==4.0.10
    - gitpython==3.1.34
    - google-api-core==2.11.1
    - google-auth==2.22.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.60.0
    - googletrans==4.0.0rc1
    - gpustat==1.1.1
    - gradio==3.34.0
    - gradio-client==1.3.0
    - greenlet==3.0.3
    - grpcio==1.51.3
    - gym==0.21.0
    - gym-notices==0.0.8
    - gymnasium==0.29.1
    - gymnasium-notices==0.0.1
    - h11==0.14.0
    - h2==3.2.0
    - h5py==3.9.0
    - hpack==3.0.0
    - hstspreload==2024.11.1
    - httpcore==1.0.6
    - httptools==0.6.4
    - httpx==0.27.2
    - huggingface-hub==0.26.1
    - humanfriendly==10.0
    - hydra-core==1.0.7
    - hyperframe==5.2.0
    - idna==2.10
    - imageio==2.31.3
    - immutabledict==3.0.0
    - importlab==0.8.1
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.1
    - iniconfig==2.0.0
    - interegular==0.3.3
    - isort==5.12.0
    - itsdangerous==2.2.0
    - jaxlib==0.4.22
    - jinja2==3.1.2
    - jiter==0.5.0
    - jmp==0.0.4
    - joblib==1.4.2
    - json5==0.9.25
    - jsonlines==4.0.0
    - jsonpatch==1.33
    - jsonpointer==2.4
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.7.1
    - keras==2.11.0
    - kiwisolver==1.4.5
    - langchain==0.1.13
    - langchain-community==0.0.29
    - langchain-core==0.1.33
    - langchain-text-splitters==0.0.1
    - langdetect==1.0.9
    - langsmith==0.1.31
    - lark==1.2.2
    - launchpad==2.0.1
    - lazy-loader==0.3
    - libclang==16.0.6
    - libcst==1.1.0
    - librosa==0.9.1
    - linkify-it-py==2.0.3
    - lit==16.0.6
    - llvmlite==0.43.0
    - lm-format-enforcer==0.10.6
    - local-attention==1.9.14
    - lxml==5.3.0
    - lz4==4.3.2
    - markdown==3.4.4
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - marshmallow==3.21.1
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.7
    - mccabe==0.7.0
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mistral-common==1.4.4
    - ml-collections==0.1.1
    - ml-dtypes==0.3.1
    - mpmath==1.3.0
    - msgpack==1.0.5
    - msgspec==0.18.6
    - multidict==6.0.4
    - multiprocess==0.70.16
    - mypy-extensions==1.0.0
    - narwhals==1.4.2
    - nest-asyncio==1.5.8
    - networkx==3.1
    - ninja==1.11.1.1
    - nltk==3.9.1
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.535.108
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.20
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - omegaconf==2.0.6
    - onnxruntime-gpu==1.19.0
    - openai==1.53.0
    - opencensus==0.11.2
    - opencensus-context==0.1.3
    - opencv-python==4.8.0.76
    - opencv-python-headless==4.10.0.84
    - opentelemetry-api==1.20.0
    - opentelemetry-exporter-otlp==1.20.0
    - opentelemetry-exporter-otlp-proto-common==1.20.0
    - opentelemetry-exporter-otlp-proto-grpc==1.20.0
    - opentelemetry-exporter-otlp-proto-http==1.20.0
    - opentelemetry-proto==1.20.0
    - opentelemetry-sdk==1.20.0
    - opentelemetry-semantic-conventions==0.41b0
    - opt-einsum==3.3.0
    - optax==0.1.7
    - orbax-checkpoint==0.4.7
    - orjson==3.9.15
    - outcome==1.3.0.post0
    - outlines==0.0.46
    - overrides==7.7.0
    - packaging==23.2
    - pandas==2.1.0
    - partial-json-parser==0.2.1.1.post4
    - pathspec==0.11.2
    - pathtools==0.1.2
    - peft==0.13.2
    - pettingzoo==1.22.3
    - pillow==10.4.0
    - pip==24.3.1
    - pipreqs==0.4.13
    - platformdirs==3.10.0
    - pluggy==1.3.0
    - pooch==1.8.2
    - portalocker==2.10.1
    - portpicker==1.6.0
    - praat-parselmouth==0.4.4
    - prometheus-client==0.21.0
    - prometheus-fastapi-instrumentator==7.0.0
    - protobuf==3.20.3
    - psutil==5.9.5
    - py-cpuinfo==9.0.0
    - py-spy==0.3.14
    - pyairports==2.1.1
    - pyarrow==18.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycnite==2023.10.11
    - pycountry==24.6.1
    - pycparser==2.22
    - pydantic==1.10.7
    - pydantic-core==2.27.1
    - pydot==1.4.2
    - pydub==0.25.1
    - pygame==2.5.1
    - pygments==2.16.1
    - pyink==23.10.0
    - pylint==3.0.2
    - pyparsing==3.0.9
    - pyproject-hooks==1.0.0
    - pysocks==1.7.1
    - pytest==7.4.3
    - pytest-xdist==3.5.0
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-louvain==0.16
    - python-multipart==0.0.9
    - pytorch-crf==0.7.2
    - pytype==2023.11.29
    - pytz==2023.3.post1
    - pywavelets==1.4.1
    - pyworld==0.3.2
    - pyyaml==6.0.1
    - pyzmq==26.2.0
    - qute==3.0.11
    - rank-bm25==0.2.2
    - rapidfuzz==3.10.1
    - ray==2.38.0
    - ray-cpp==2.6.1
    - reactivex==4.0.4
    - referencing==0.30.2
    - regex==2024.7.24
    - requests==2.32.3
    - requests-oauthlib==1.3.1
    - resampy==0.4.3
    - reverb==2.0.1
    - rfc3986==1.5.0
    - rich==13.5.2
    - rpds-py==0.10.2
    - rsa==4.9
    - sacrebleu==2.4.3
    - safetensors==0.4.5
    - scikit-image==0.21.0
    - scikit-learn==1.4.2
    - scipy==1.11.2
    - scribble==1.0.0
    - selenium==4.9.1
    - semantic-version==2.10.0
    - sentencepiece==0.2.0
    - sentry-sdk==1.30.0
    - setproctitle==1.3.2
    - setuptools==75.6.0
    - shtab==1.7.1
    - six==1.16.0
    - smart-open==6.4.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soundfile==0.12.1
    - sqlalchemy==2.0.28
    - stable-baselines3==1.8.0
    - starlette==0.41.2
    - supersuit==3.7.2
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.3
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.2.dev38+gce08ab4
    - tensorflow==2.11.1
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.33.0
    - tensorflow-probability==0.23.0
    - tensorstore==0.1.51
    - termcolor==2.3.0
    - textblob==0.18.0.post0
    - threadpoolctl==3.5.0
    - thulac==0.2.2
    - tifffile==2023.8.30
    - tiktoken==0.7.0
    - tinyscaler==1.2.7
    - tokenizers==0.20.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.12.3
    - toolz==0.12.0
    - torch==2.4.0
    - torch-geometric==2.5.3
    - torchaudio==2.4.0
    - torchcrepe==0.0.20
    - torchfcpe==0.0.4
    - torchtext==0.18.0
    - torchvision==0.19.0
    - tornado==6.3.2
    - tqdm==4.66.6
    - traitlets==5.14.3
    - transformers==4.45.2
    - trio==0.25.1
    - trio-websocket==0.11.1
    - triton==3.0.0
    - trl==0.11.4
    - typer==0.9.0
    - typing-extensions==4.12.2
    - typing-inspect==0.9.0
    - tyro==0.8.14
    - tzdata==2023.3
    - uc-micro-py==1.0.3
    - urllib3==1.26.16
    - uvicorn==0.23.2
    - uvloop==0.21.0
    - virtualenv==20.21.0
    - vllm==0.6.3.post1
    - wandb==0.15.10
    - watchfiles==0.24.0
    - wcwidth==0.2.6
    - websocket-client==1.8.0
    - websockets==12.0
    - werkzeug==3.0.6
    - wheel==0.45.1
    - wrapt==1.14.1
    - wsproto==1.2.0
    - xformers==0.0.27.post2
    - xxhash==3.5.0
    - yarg==0.1.9
    - yarl==1.9.2
    - zipp==3.16.2